# Gunakan base image PHP Apache yang stabil
FROM php:8.1-apache
# Set working directory
WORKDIR /app
# 1. Install System Dependencies (Wajib untuk PHP Extension)
RUN apt-get update && apt-get install -y libicu-dev libpng-dev
libzip-dev libonig-dev libjpeg62-turbo-dev libfreetype6-dev
unzip git && rm -rf /var/lib/apt/lists/*
# 2. Configure & Install PHP Extensions (Penyebab Error Sebelumnya)

RUN docker-php-ext-configure gd --with-freetype --with-jpeg && docker-php-
ext-install intl gd zip mysqli pdo_mysql mbstring

bcmath
# 3. Aktifkan Apache Rewrite Module (Penting untuk CI4 Routing)
RUN a2enmod rewrite
COPY docker/apache/000-default.conf /etc/apache2/sites-available/000-
default.conf
# 4. Install Composer (Ambil dari image resmi)
COPY --from=composer:latest /usr/bin/composer /usr/bin/composer
# 5. Copy Composer files dulu (Optimasi Docker Cache)
COPY composer.json composer.lock ./

3. Kenapa Ini Menyelesaikan Masalah?
Penyediaan Library: Penambahan libicu-dev memungkinkan ekstensi intl
(Internationalization) terinstall. Tanpa ini, CodeIgniter 4 tidak bisa jalan.
Layer Caching: Dengan meng-copy composer.json sebelum sisa kode, build
selanjutnya akan jauh lebih cepat jika tidak ada perubahan library.
Apache Config: Memastikan routing CI4 di /public terbaca dengan benar
oleh Apache.

Generated by DevOps Tutor - Fokus pada Stabilitas dan Keamanan Pipeline.

# 6. Jalankan Composer Install
# --no-dev: untuk production, --optimize-autoloader: performa maksimal

RUN composer install --no-dev --no-interaction --optimize-autoloader --ignore-
platform-reqs

# 7. Copy seluruh Source Code
COPY . .
# 8. Set Permissions (Agar tidak Error Permission Denied di K8s)
RUN chown -R www-data:www-data /app/writable /app/public/uploads
# Expose port 80
EXPOSE 80
